project:
  type: website

website:
  title: "Anyhow SG Smarthome"
  navbar:
    left:
      - text: Articles
        href: articles.qmd
      - text: Docs
        menu:
          - text: Home Assistant
            href: home-assistant/index.qmd
          - text: LED
            href: led/index.qmd
    right:
      - about.qmd
      - icon: github
        href: https://github.com/anyhow-sg-smarthome
format:
  html:
    theme: cosmo
    css: styles.css



